Style/AsciiComments:
  Enabled: false
Style/MultilineMethodCallIndentation:
  Enabled: false
Style/MultilineOperationIndentation:
  Enabled: false
Style/AlignParameters:
  Enabled: false
AllCops:
  Exclude:
    - 'path/to/excluded/file.rb'
